namespace Database.Persistence;

internal static class DefaultSeedData
{
    public static IReadOnlyList<CategoryEntity> Categories { get; } =
    [
        new() { CategoryId = 1, Name = "Graphics", Description = "Graphics viewers, editors, graphics demos, screensavers etc." },
        new() { CategoryId = 2, Name = "Browsers", Description = "Netscape, Opera, Mozilla, Mosaic, IE, ..." },
        new() { CategoryId = 3, Name = "Email, news and Groupware", Description = "Email and related programs." },
        new() { CategoryId = 4, Name = "Chat, Instant Messaging, Telephony", Description = "Telegram, Teams, Skype, Zoom, ..." },
        new() { CategoryId = 5, Name = "Programming/Software Engineering", Description = "Languages, Compilers, IDEs, CASE tools etc." },
        new() { CategoryId = 6, Name = "Utilities", Description = "Misc. Utilities" },
        new() { CategoryId = 7, Name = "Scientific/Technical/Math", Description = "Scientific and mathematic applications" },
        new() { CategoryId = 8, Name = "File System", Description = "File System Utilities (e.g. CD writer stuff, file managers, shells, ...)" },
        new() { CategoryId = 9, Name = "Office Suites", Description = "Productivity apps that contain bundles of applications." },
        new() { CategoryId = 10, Name = "CAD/CAE", Description = "Computer Aided Design, Computer Aided Engineering" },
        new() { CategoryId = 11, Name = "Games", Description = "Games" },
        new() { CategoryId = 12, Name = "Sound Editing", Description = "Sound editing suites, recorders, mixing and sampling." },
        new() { CategoryId = 13, Name = "Audio Players", Description = "MP3, WAV, and other format audio players." },
        new() { CategoryId = 14, Name = "Graphics Viewer", Description = "Image viewing" },
        new() { CategoryId = 15, Name = "Graphics Editing", Description = "Image editing/vector drawing software" },
        new() { CategoryId = 16, Name = "Animation/Rendering/3D", Description = "Image animation for multimedia or web" },
        new() { CategoryId = 17, Name = "Audio", Description = "Audio related applications" },
        new() { CategoryId = 18, Name = "Video", Description = "Video players, editors and codecs" },
        new() { CategoryId = 19, Name = "Compression", Description = "Compression Tools" },
        new() { CategoryId = 20, Name = "Word Processing", Description = "Type, edit, print, OCR!" },
        new() { CategoryId = 21, Name = "Spreadsheet", Description = "Do it yourself Number crunching" },
        new() { CategoryId = 22, Name = "Database", Description = "Relational Database" },
        new() { CategoryId = 23, Name = "Presentation", Description = "Slide Shows with animation and sound and flowchart tools" },
        new() { CategoryId = 24, Name = "Web Design", Description = "Create your own web page" },
        new() { CategoryId = 25, Name = "Multimedia", Description = "Graphics, Audio and Video" },
        new() { CategoryId = 26, Name = "Productivity", Description = "Productivity applications" },
        new() { CategoryId = 27, Name = "Networking & Communication", Description = "Network, Internet related programs and comm stuff" },
        new() { CategoryId = 28, Name = "Net Tools", Description = "Tools such as proxies, web crawlers, search engines, ..." },
        new() { CategoryId = 29, Name = "Reference/Documentation/Info", Description = "Encyclopedias, information resources, data tracking, ..." },
        new() { CategoryId = 30, Name = "EDA/Measurement", Description = "Electronics design tools, measurement and stuff" },
        new() { CategoryId = 31, Name = "Mathematics", Description = "Mathematical and Statistical software." },
        new() { CategoryId = 32, Name = "Text Editors", Description = "Multipurpose text editing tool. No formatting just text." },
        new() { CategoryId = 33, Name = "Office Utilities", Description = "Misc Office tools that usually work in conjunction with other Office software." },
        new() { CategoryId = 34, Name = "Finance/Accounting/Project/CRM", Description = "Personal and Business Finance Software and project planning, CRM (Customer Relationship Management)." },
        new() { CategoryId = 35, Name = "Flowchart/Diagraming/graphs", Description = "Software to design flowcharts and diagrams" },
        new() { CategoryId = 36, Name = "File transfer/sharing", Description = "FTP, NFS, document sharing, Samba, scp, ..." },
        new() { CategoryId = 37, Name = "Installers", Description = "Program installers like installshield, windows installer etc." },
        new() { CategoryId = 38, Name = "Remote Access", Description = "SSH, Telnet, VNC, Terminal Services, ..." },
        new() { CategoryId = 39, Name = "Educational games / children", Description = "Games that encourage learning." },
        new() { CategoryId = 40, Name = "Card, Puzzle and Board Games", Description = "Card Games, mind puzzles and other stuff." },
        new() { CategoryId = 41, Name = "Educational Software, CBT", Description = "Educational tools, Computer Based Training" },
        new() { CategoryId = 42, Name = "Action Games", Description = "Arcade and platform action games" },
        new() { CategoryId = 43, Name = "Sports Games", Description = "Professional sports, car racing, and more." },
        new() { CategoryId = 44, Name = "Simulation Games", Description = "Flight and other real life simulators." },
        new() { CategoryId = 45, Name = "Adventures", Description = "Graphical Adventure Games" },
        new() { CategoryId = 46, Name = "Online (MMORPG) Games", Description = "Massively Multiplayer Online Role Playing Games." },
        new() { CategoryId = 47, Name = "1st Person Shooter", Description = "Games such as Doom, Quake, Half-Life." },
        new() { CategoryId = 48, Name = "Role Playing Games", Description = "Games where you build up your characters through battle and experience." },
        new() { CategoryId = 49, Name = "Strategy Games", Description = "Build your army, conquer the world" },
        new() { CategoryId = 50, Name = "Game Tools", Description = "Misc. tools related to games." },
        new() { CategoryId = 51, Name = "Emulators", Description = "Software that emulates game hardware." },
        new() { CategoryId = 52, Name = "Desktop Publishing", Description = "Various page layout, print, and publishing applications." },
        new() { CategoryId = 53, Name = "Astronomy", Description = "An endless (almost) empty space... ;-)" }
    ];
}
